quarkus.dynamodb.aws.region=us-east-1
quarkus.dynamodb.aws.credentials.type=default
quarkus.dynamodb.sync-client.type=url
quarkus.dynamodb.devservices.enabled=false

fittrack.claude.api-key=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
fittrack.claude.model=claude-opus-4-5

mp.jwt.verify.issuer=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_FiMxzIAMO
mp.jwt.verify.publickey.location=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_FiMxzIAMO/.well-known/jwks.json
quarkus.smallrye-jwt.enabled=false

quarkus.package.jar.type=legacy-jar

quarkus.lambda.handler=io.quarkus.amazon.lambda.http.LambdaHttpHandler
quarkus.http.host=0.0.0.0

quarkus.http.root-path=/